"""
Shows how to generate an image variation from a source image with the
Amazon Titan Image Generator G1 model (on demand).
"""
import base64
import io
import json
import logging
import boto3
from PIL import Image

from botocore.exceptions import ClientError


class ImageError(Exception):
    "Custom exception for errors returned by Amazon Titan Image Generator G1"

    def __init__(self, message):
        self.message = message


logger = logging.getLogger(__name__)
logging.basicConfig(level=logging.INFO)

def resize_image(image_bytes, target_size):
    """
    Resize an image to the target size.
    Args:
        image_bytes (bytes): The image bytes to resize.
        target_size (tuple): The target size as (width, height).
    Returns:
        resized_image_bytes (bytes): The resized image bytes.
    """
    img = Image.open(io.BytesIO(image_bytes))
    original_format = img.format or 'PNG'
    img = img.resize(target_size, Image.Resampling.LANCZOS)
    byte_arr = io.BytesIO()
    img.save(byte_arr, format=original_format)
    byte_arr.seek(0)
    return byte_arr.getvalue()

def generate_image(model_id, body):
    """
    Generate an image using Amazon Titan Image Generator G1 model on demand.
    Args:
        model_id (str): The model ID to use.
        body (str) : The request body to use.
    Returns:
        image_bytes (bytes): The image generated by the model.
    """

    logger.info(
        "Generating image with Amazon Titan Image Generator G1 model %s", model_id)

    bedrock = boto3.client(service_name='bedrock-runtime', region_name='us-east-1')

    accept = "application/json"
    content_type = "application/json"

    response = bedrock.invoke_model(
        body=body, modelId=model_id, accept=accept, contentType=content_type
    )
    response_body = json.loads(response.get("body").read())

    base64_image = response_body.get("images")[0]
    base64_bytes = base64_image.encode('ascii')
    image_bytes = base64.b64decode(base64_bytes)

    finish_reason = response_body.get("error")

    if finish_reason is not None:
        raise ImageError(f"Image generation error. Error is {finish_reason}")

    logger.info(
        "Successfully generated image with Amazon Titan Image Generator G1 model %s", model_id)

    return image_bytes


def main():
    """
    Entrypoint for Amazon Titan Image Generator G1 example.
    """
    try:
        logging.basicConfig(level=logging.INFO,
                            format="%(levelname)s: %(message)s")

        model_id = 'amazon.titan-image-generator-v2:0'

        # Read image from S3 and encode it as base64 string.
        s3_bucket = "lab-genai-gal12012026"
        s3_key = "art_deco/data/livingroom.png"
        
        s3 = boto3.client(service_name='s3')
        response = s3.get_object(Bucket=s3_bucket, Key=s3_key)
        image_data = response['Body'].read()
        resized_image_data = resize_image(image_data, (512, 512))
        input_image = base64.b64encode(resized_image_data).decode('utf8')

        body = json.dumps({
            "taskType": "INPAINTING",
            "inPaintingParams": {
                "text": "Remove the cat from the sofa. Your answer must have no cats sitting on the sofa.",
                "negativeText": "bad quality, low res",
                "maskPrompt": "Cat on the sofa",
                "image": input_image,
            },
            "imageGenerationConfig": {
                "numberOfImages": 1,
                "height": 512,
                "width": 512,
                "cfgScale": 10.0
            }
        })

        image_bytes = generate_image(model_id=model_id,
                                     body=body)
        image = Image.open(io.BytesIO(image_bytes))
        
        # Save the generated image
        output_path = "generated_image.png"
        image.save(output_path)
        logger.info(f"Image saved to {output_path}")
        
        image.show()

    except ClientError as err:
        message = err.response["Error"]["Message"]
        logger.error("A client error occurred: %s", message)
        print("A client error occured: " +
              format(message))
    except ImageError as err:
        logger.error(err.message)
        print(err.message)

    else:
        print(
            f"Finished generating image with Amazon Titan Image Generator G1 model {model_id}.")


if __name__ == "__main__":
    main()
